using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Ravelaso.UiPath.InvoiceExtract.Generators;

[Generator]
#pragma warning disable RS1036
public sealed class InvoiceActivityGenerator : ISourceGenerator
#pragma warning restore RS1036
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new TypeReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var compilation = context.Compilation;

        var invoiceProfileAttributeSymbol = compilation.GetTypeByMetadataName(
            "Ravelaso.UiPath.InvoiceExtract.Core.InvoiceProfileAttribute");

        var invoiceProcessorSymbol = compilation.GetTypeByMetadataName(
            "Ravelaso.UiPath.InvoiceExtract.Core.Interfaces.IInvoiceProcessor`1");

        if (invoiceProfileAttributeSymbol is null || invoiceProcessorSymbol is null)
            return;

        if (context.SyntaxReceiver is not TypeReceiver receiver)
            return;

        foreach (var candidate in receiver.Candidates)
        {
            var semanticModel = compilation.GetSemanticModel(candidate.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(candidate) is not INamedTypeSymbol processorSymbol)
                continue;

            if (processorSymbol.TypeKind != TypeKind.Class || processorSymbol.IsAbstract)
                continue;

            var profileAttribute = processorSymbol
                .GetAttributes()
                .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, invoiceProfileAttributeSymbol));

            if (profileAttribute is null)
                continue;

            var processorInterface = processorSymbol.AllInterfaces
                .FirstOrDefault(i =>
                    SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, invoiceProcessorSymbol));

            if (processorInterface is null)
                continue;

            var dataTypeSymbol = processorInterface.TypeArguments[0] as INamedTypeSymbol;
            if (dataTypeSymbol is null)
                continue;

            var profileKey = profileAttribute.ConstructorArguments.Length > 0
                ? profileAttribute.ConstructorArguments[0].Value?.ToString()
                : null;

            if (string.IsNullOrWhiteSpace(profileKey))
                continue;

            var displayName = profileAttribute.NamedArguments
                .FirstOrDefault(x => x.Key == "DisplayName")
                .Value.Value?.ToString();

            var processorNamespace = processorSymbol.ContainingNamespace.ToDisplayString();
            var dataNamespace = dataTypeSymbol.ContainingNamespace.ToDisplayString();

            var processorName = processorSymbol.Name;
            var dataTypeName = dataTypeSymbol.Name;

            var safeProfileName = SanitizeIdentifier(profileKey);
            var generatedTypeName = $"{safeProfileName}InvoiceProfile";

            var namespaces = new[]
                {
                    processorNamespace,
                    dataNamespace
                }
                .Where(static ns => !string.IsNullOrWhiteSpace(ns))
                .Distinct()
                .OrderBy(static ns => ns)
                .Select(static ns => $"using {ns};");

            var usingBlock = "// <auto-generated/>\n" +
                             string.Join("\n", namespaces);

            var source =
                $$"""
                  {{usingBlock}}

                  namespace Ravelaso.UiPath.InvoiceExtract.Generated;

                  public static class {{generatedTypeName}}
                  {
                      public const string Key = "{{profileKey}}";
                      public const string? DisplayName = {{(displayName is null ? "null" : $"@\"{Escape(displayName)}\"")}};

                      public static {{processorName}} CreateProcessor()
                      {
                          return new {{processorName}}();
                      }
                  }
                  """;

            context.AddSource($"{generatedTypeName}.g.cs", source);
        }
    }

    private static string SanitizeIdentifier(string? value)
    {
        var chars = value!
            .Select(ch => char.IsLetterOrDigit(ch) ? ch : '_')
            .ToArray();

        var result = new string(chars);

        if (string.IsNullOrWhiteSpace(result))
            return "Invoice";

        if (char.IsDigit(result[0]))
            result = "_" + result;

        return result;
    }

    private static string Escape(string value)
    {
        return value.Replace("\"", "\"\"");
    }

    private sealed class TypeReceiver : ISyntaxReceiver
    {
        public List<TypeDeclarationSyntax> Candidates { get; } = [];

        public void OnVisitSyntaxNode(SyntaxNode node)
        {
            if (node is ClassDeclarationSyntax classDeclaration)
                Candidates.Add(classDeclaration);
        }
    }
}