using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Ravelaso.UiPath.InvoiceExtract.Generators;

[Generator]
#pragma warning disable RS1036
public sealed class InvoiceUiPathActivityGenerator : ISourceGenerator
#pragma warning restore RS1036
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(static () => new TypeReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var compilation = context.Compilation;

        var invoiceProfileAttributeSymbol = compilation.GetTypeByMetadataName(
            "Ravelaso.UiPath.InvoiceExtract.Core.InvoiceProfileAttribute");

        var invoiceProcessorSymbol = compilation.GetTypeByMetadataName(
            "Ravelaso.UiPath.InvoiceExtract.Core.Interfaces.IInvoiceProcessor`1");

        if (invoiceProfileAttributeSymbol is null || invoiceProcessorSymbol is null)
            return;

        if (context.SyntaxReceiver is not TypeReceiver receiver)
            return;

        foreach (var candidate in receiver.Candidates)
        {
            var semanticModel = compilation.GetSemanticModel(candidate.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(candidate) is not INamedTypeSymbol processorSymbol)
                continue;

            if (processorSymbol.TypeKind != TypeKind.Class || processorSymbol.IsAbstract)
                continue;

            var profileAttribute = processorSymbol
                .GetAttributes()
                .FirstOrDefault(attribute =>
                    SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, invoiceProfileAttributeSymbol));

            if (profileAttribute is null)
                continue;

            var processorInterface = processorSymbol.AllInterfaces
                .FirstOrDefault(@interface =>
                    SymbolEqualityComparer.Default.Equals(@interface.OriginalDefinition, invoiceProcessorSymbol));

            if (processorInterface is null)
                continue;

            if (processorInterface.TypeArguments[0] is not INamedTypeSymbol dataTypeSymbol)
                continue;

            var profileKey = profileAttribute.ConstructorArguments.Length > 0
                ? profileAttribute.ConstructorArguments[0].Value as string
                : null;

            if (string.IsNullOrWhiteSpace(profileKey))
                continue;

            var displayName = profileAttribute.NamedArguments
                .FirstOrDefault(argument => argument.Key == "DisplayName")
                .Value.Value as string;

            var namespaceName = processorSymbol.ContainingNamespace.ToDisplayString();
            var processorName = processorSymbol.Name;
            var dataTypeName = dataTypeSymbol.Name;

            var safeProfileName = SanitizeIdentifier(profileKey);
            var activityName = "Extract" + safeProfileName + "Invoice";
            var activityDisplayName = string.IsNullOrWhiteSpace(displayName)
                ? "Extract " + profileKey + " Invoice"
                : displayName;

            var source =
                $$"""
                  // <auto-generated/>
                  using System;
                  using System.Activities;
                  using System.ComponentModel;
                  using System.Diagnostics;
                  using {{namespaceName}};
                  using Ravelaso.UiPath.InvoiceExtract.Core.Helpers;
                  using UiPath.Robot.Activities.Api;

                  namespace Ravelaso.UiPath.InvoiceExtract;

                  [DisplayName({{VerbatimQuote(activityDisplayName)}})]
                  public sealed class {{activityName}} : CodeActivity
                  {
                      [RequiredArgument]
                      [DisplayName("File Path (Input)")]
                      public InArgument<string> FilePath { get; set; }

                      [RequiredArgument]
                      [DisplayName("{{dataTypeName}} (Output)")]
                      public OutArgument<{{dataTypeName}}> Result { get; set; }

                      protected override void Execute(CodeActivityContext context)
                      {
                          try
                          {
                              var pdfPath = FilePath.Get(context);
                              var processor = new {{processorName}}();
                              var data = InvoiceHelper.ProcessInvoice(processor, pdfPath);
                              Result.Set(context, data);
                          }
                          catch (Exception e)
                          {
                              var runtime = context.GetExtension<IExecutorRuntime>();
                              if (runtime is not null)
                              {
                                  runtime.LogMessage(new LogMessage
                                  {
                                      EventType = TraceEventType.Error,
                                      Message = e.Message
                                  });
                              }

                              throw;
                          }
                      }
                  }
                  """;

            context.AddSource(activityName + ".g.cs", source);
        }
    }

    private static string SanitizeIdentifier(string? value)
    {
        var chars = (value ?? string.Empty)
            .Select(static ch => char.IsLetterOrDigit(ch) ? ch : '_')
            .ToArray();

        var result = new string(chars);

        if (string.IsNullOrWhiteSpace(result))
            return "Invoice";

        if (char.IsDigit(result[0]))
            result = "_" + result;

        return result;
    }

    private static string VerbatimQuote(string? value)
    {
        return "@\"" + value?.Replace("\"", "\"\"") + "\"";
    }

    private sealed class TypeReceiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> Candidates { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode node)
        {
            if (node is ClassDeclarationSyntax classDeclaration)
                Candidates.Add(classDeclaration);
        }
    }
}