using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Ravelaso.UiPath.InvoiceExtract.Generators;

[Generator]
#pragma warning disable RS1036
public sealed class InvoiceCatalogGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new CatalogTypeReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var compilation = context.Compilation;

        var invoiceProfileAttributeSymbol = compilation.GetTypeByMetadataName(
            "Ravelaso.UiPath.InvoiceExtract.Core.InvoiceProfileAttribute");

        var invoiceProcessorSymbol = compilation.GetTypeByMetadataName(
            "Ravelaso.UiPath.InvoiceExtract.Core.Interfaces.IInvoiceProcessor`1");

        var invoiceDataSymbol = compilation.GetTypeByMetadataName(
            "Ravelaso.UiPath.InvoiceExtract.Core.Interfaces.IInvoiceData");

        if (invoiceProfileAttributeSymbol is null || invoiceProcessorSymbol is null || invoiceDataSymbol is null)
            return;

        if (context.SyntaxReceiver is not CatalogTypeReceiver receiver)
            return;

        var registrations = new List<CatalogRegistration>();

        foreach (var candidate in receiver.Candidates)
        {
            var semanticModel = compilation.GetSemanticModel(candidate.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(candidate) is not { } processorSymbol)
                continue;

            if (processorSymbol.TypeKind != TypeKind.Class || processorSymbol.IsAbstract)
                continue;

            var profileAttribute = processorSymbol
                .GetAttributes()
                .FirstOrDefault(attribute =>
                    SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, invoiceProfileAttributeSymbol));

            if (profileAttribute is null)
                continue;

            var processorInterface = processorSymbol.AllInterfaces
                .FirstOrDefault(@interface =>
                    SymbolEqualityComparer.Default.Equals(@interface.OriginalDefinition, invoiceProcessorSymbol));

            if (processorInterface?.TypeArguments[0] is not INamedTypeSymbol dataTypeSymbol)
                continue;

            if (!ImplementsInterface(dataTypeSymbol, invoiceDataSymbol))
                continue;

            var profileKey = profileAttribute.ConstructorArguments.Length > 0
                ? profileAttribute.ConstructorArguments[0].Value as string
                : null;

            if (string.IsNullOrWhiteSpace(profileKey))
                continue;

            var displayName = profileAttribute.NamedArguments
                .FirstOrDefault(argument => argument.Key == "DisplayName")
                .Value.Value as string;

            registrations.Add(new CatalogRegistration(
                ProfileKey: profileKey!,
                DisplayName: displayName,
                ProcessorFullName: processorSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                DataTypeFullName: dataTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                PropertyName: SanitizePropertyName(profileKey)));
        }

        if (registrations.Count == 0)
            return;

        context.AddSource("InvoiceRegistration.g.cs", GenerateRegistrationSource());
        context.AddSource("InvoiceCatalog.g.cs", GenerateCatalogSource(registrations));
    }

    private static bool ImplementsInterface(INamedTypeSymbol type, INamedTypeSymbol interfaceSymbol)
    {
        return type.AllInterfaces.Any(@interface =>
            SymbolEqualityComparer.Default.Equals(@interface, interfaceSymbol) ||
            SymbolEqualityComparer.Default.Equals(@interface.OriginalDefinition, interfaceSymbol));
    }

    private static string GenerateRegistrationSource()
    {
        return
            """
            // <auto-generated/>
            #nullable enable
            using System;

            namespace Ravelaso.UiPath.InvoiceExtract.Generated;

            public interface IInvoiceRegistration
            {
                string Key { get; }
                string? DisplayName { get; }
                Type DataType { get; }
                Type ProcessorType { get; }
                object CreateProcessor();
            }

            public sealed record InvoiceRegistration<TProcessor, TData>(
                string Key,
                string? DisplayName)
                : IInvoiceRegistration
                where TProcessor : class, Ravelaso.UiPath.InvoiceExtract.Core.Interfaces.IInvoiceProcessor<TData>, new()
                where TData : Ravelaso.UiPath.InvoiceExtract.Core.Interfaces.IInvoiceData
            {
                public Type DataType => typeof(TData);
                public Type ProcessorType => typeof(TProcessor);

                public TProcessor CreateProcessor() => new TProcessor();

                object IInvoiceRegistration.CreateProcessor() => CreateProcessor();
            }
            """;
    }

    private static string GenerateCatalogSource(IReadOnlyList<CatalogRegistration> registrations)
    {
        var typedProperties = string.Join("\n\n    ",
            registrations.Select(r =>
                $$"""
                  public static InvoiceRegistration<{{r.ProcessorFullName}}, {{r.DataTypeFullName}}> {{r.PropertyName}} { get; } =
                      new({{Quote(r.ProfileKey)}}, {{(r.DisplayName is null ? "null" : VerbatimQuote(r.DisplayName))}});
                  """));

        var allItems = string.Join(",\n        ",
            registrations.Select(r => r.PropertyName));

        var keysItems = string.Join(",\n        ",
            registrations.Select(r => Quote(r.ProfileKey)));

        return
            $$"""
              // <auto-generated/>
              #nullable enable
              using System;
              using System.Collections.Generic;
              using System.Linq;

              namespace Ravelaso.UiPath.InvoiceExtract.Generated;

              public static class InvoiceCatalog
              {
                  {{typedProperties}}

                  public static IReadOnlyList<IInvoiceRegistration> All { get; } = new IInvoiceRegistration[]
                  {
                      {{allItems}}
                  };

                  public static IReadOnlyList<string> Keys { get; } = new[]
                  {
                      {{keysItems}}
                  };
              }
              """;
    }

    private static string SanitizePropertyName(string? value)
    {
        var chars = (value ?? string.Empty)
            .Select(static ch => char.IsLetterOrDigit(ch) ? ch : '_')
            .ToArray();

        var result = new string(chars);

        if (string.IsNullOrWhiteSpace(result))
            return "Invoice";

        if (char.IsDigit(result[0]))
            result = "_" + result;

        return result;
    }

    private static string Quote(string? value)
    {
        return "\"" + value?.Replace("\"", "\\\"") + "\"";
    }

    private static string VerbatimQuote(string? value)
    {
        return "@\"" + (value ?? string.Empty).Replace("\"", "\"\"") + "\"";
    }

    private sealed class CatalogTypeReceiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> Candidates { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode node)
        {
            if (node is ClassDeclarationSyntax classDeclaration)
                Candidates.Add(classDeclaration);
        }
    }

    private sealed record CatalogRegistration(
        string ProfileKey,
        string? DisplayName,
        string ProcessorFullName,
        string DataTypeFullName,
        string PropertyName)
    {
        public string ProfileKey { get; } = ProfileKey;
        public string? DisplayName { get; } = DisplayName;
        public string ProcessorFullName { get; } = ProcessorFullName;
        public string DataTypeFullName { get; } = DataTypeFullName;
        public string PropertyName { get; } = PropertyName;
    }
}
