using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Ravelaso.UiPath.InvoiceExtract.Generators;

[Generator]
#pragma warning disable RS1036
public sealed class InvoiceCatalogGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new CatalogTypeReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var compilation = context.Compilation;

        var invoiceProfileAttributeSymbol = compilation.GetTypeByMetadataName(
            "Ravelaso.UiPath.InvoiceExtract.Core.InvoiceProfileAttribute");

        var invoiceProcessorSymbol = compilation.GetTypeByMetadataName(
            "Ravelaso.UiPath.InvoiceExtract.Core.Interfaces.IInvoiceProcessor`1");

        if (invoiceProfileAttributeSymbol is null || invoiceProcessorSymbol is null)
            return;

        if (context.SyntaxReceiver is not CatalogTypeReceiver receiver)
            return;

        var registrations = new List<CatalogRegistration>();

        foreach (var candidate in receiver.Candidates)
        {
            var semanticModel = compilation.GetSemanticModel(candidate.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(candidate) is not { } processorSymbol)
                continue;

            if (processorSymbol.TypeKind != TypeKind.Class || processorSymbol.IsAbstract)
                continue;

            var profileAttribute = processorSymbol
                .GetAttributes()
                .FirstOrDefault(attribute =>
                    SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, invoiceProfileAttributeSymbol));

            if (profileAttribute is null)
                continue;

            var processorInterface = processorSymbol.AllInterfaces
                .FirstOrDefault(@interface =>
                    SymbolEqualityComparer.Default.Equals(@interface.OriginalDefinition, invoiceProcessorSymbol));

            if (processorInterface is null)
                continue;

            if (processorInterface.TypeArguments[0] is not INamedTypeSymbol dataTypeSymbol)
                continue;

            var profileKey = profileAttribute.ConstructorArguments.Length > 0
                ? profileAttribute.ConstructorArguments[0].Value as string
                : null;

            if (string.IsNullOrWhiteSpace(profileKey))
                continue;

            var displayName = profileAttribute.NamedArguments
                .FirstOrDefault(argument => argument.Key == "DisplayName")
                .Value.Value as string;

            if (profileKey != null)
                registrations.Add(new CatalogRegistration(
                    ProfileKey: profileKey,
                    DisplayName: displayName,
                    ProcessorFullName: processorSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    DataTypeFullName: dataTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    EnumMemberName: SanitizeEnumMemberName(profileKey)));
        }

        if (registrations.Count == 0)
            return;

        context.AddSource("InvoiceProfileKey.g.cs", GenerateEnumSource(registrations));
        context.AddSource("InvoiceCatalog.g.cs", GenerateCatalogSource(registrations));
    }

    private static string GenerateEnumSource(IReadOnlyList<CatalogRegistration> registrations)
    {
        var members = string.Join(",\n    ",
            registrations.Select(r =>
                $"[System.Runtime.Serialization.EnumMember(Value = {Quote(r.ProfileKey)})] {r.EnumMemberName}"));

        return
            $$"""
              // <auto-generated/>
              #nullable enable
              using System.Runtime.Serialization;

              namespace Ravelaso.UiPath.InvoiceExtract.Generated;

              public enum InvoiceProfileKey
              {
                  {{members}}
              }
              """;
    }

    private static string GenerateCatalogSource(IReadOnlyList<CatalogRegistration> registrations)
    {
        var items = string.Join(",\n        ",
            registrations.Select(r =>
                $$"""new InvoiceRegistration({{Quote(r.ProfileKey)}}, {{(r.DisplayName is null ? "null" : VerbatimQuote(r.DisplayName))}}, typeof({{r.DataTypeFullName}}), typeof({{r.ProcessorFullName}}), () => new {{r.ProcessorFullName}}())"""));

        return
            $$"""
              // <auto-generated/>
              #nullable enable
              using System;
              using System.Collections.Generic;
              using System.Linq;

              namespace Ravelaso.UiPath.InvoiceExtract.Generated;

              public sealed record InvoiceRegistration(
                  string Key,
                  string? DisplayName,
                  Type DataType,
                  Type ProcessorType,
                  Func<object> CreateProcessor);

              public static class InvoiceCatalog
              {
                  private static readonly IReadOnlyList<InvoiceRegistration> _all = new[]
                  {
                      {{items}}
                  };

                  private static readonly IReadOnlyDictionary<string, InvoiceRegistration> _byKey =
                      _all.ToDictionary(x => x.Key, StringComparer.OrdinalIgnoreCase);

                  public static IReadOnlyList<InvoiceRegistration> All => _all;

                  public static IReadOnlyList<string> Keys => _all.Select(x => x.Key).ToArray();

                  public static bool TryGetByKey(string key, out InvoiceRegistration registration)
                  {
                      if (string.IsNullOrWhiteSpace(key))
                      {
                          registration = default!;
                          return false;
                      }

                      return _byKey.TryGetValue(key, out registration!);
                  }

                  public static InvoiceRegistration GetByKey(string key)
                  {
                      if (TryGetByKey(key, out var registration))
                          return registration;

                      throw new KeyNotFoundException($"No invoice registration was generated for key '{key}'.");
                  }

                  public static InvoiceRegistration Get(InvoiceProfileKey key)
                  {
                      return GetByKey(key.ToString());
                  }
              }
              """;
    }

    private static string SanitizeEnumMemberName(string? value)
    {
        var chars = (value ?? string.Empty)
            .Select(static ch => char.IsLetterOrDigit(ch) ? ch : '_')
            .ToArray();

        var result = new string(chars);

        if (string.IsNullOrWhiteSpace(result))
            return "Unknown";

        if (char.IsDigit(result[0]))
            result = "_" + result;

        return result;
    }

    private static string Quote(string? value)
    {
        return "\"" + value?.Replace("\"", "\\\"") + "\"";
    }

    private static string VerbatimQuote(string value)
    {
        return "@\"" + value.Replace("\"", "\"\"") + "\"";
    }

    private sealed class CatalogTypeReceiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> Candidates { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode node)
        {
            if (node is ClassDeclarationSyntax classDeclaration)
                Candidates.Add(classDeclaration);
        }
    }

    private sealed record CatalogRegistration(
        string ProfileKey,
        string? DisplayName,
        string ProcessorFullName,
        string DataTypeFullName,
        string EnumMemberName)
    {
        public string ProfileKey { get; } = ProfileKey;
        public string? DisplayName { get; } = DisplayName;
        public string ProcessorFullName { get; } = ProcessorFullName;
        public string DataTypeFullName { get; } = DataTypeFullName;
        public string EnumMemberName { get; } = EnumMemberName;
    }
}
